[theme]
base="light"
primaryColor="#00ADB5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F0F0"
textColor="#000000"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
